services:
  db:
    image: postgres:16-alpine
    container_name: auth-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: auth-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=auth_db;Username=admin;Password=password123"
      Jwt__Key: "your_super_secret_key_that_is_long_enough_32_chars"
      Jwt__Issuer: "auth-api"
      Jwt__Audience: "auth-frontend"
    ports:
      - "5285:8080"
    depends_on:
      - db
    networks:
      - auth-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auth-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  postgres_data:
